version: '3.1'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=odoo_db
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: always

  odoo:
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - PGDATABASE=odoo_db
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons  # Para agregar addons personalizados
      - ./config:/etc/odoo  # Puedes almacenar configuraciones personalizadas aquí
      - ./enterprise:/mnt/enterprise
    restart: always

volumes:
  odoo-db-data:
  odoo-web-data:
